# Generated by Django 5.0.1 on 2024-01-16 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "group_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("group_picture", models.ImageField(upload_to="assets/group")),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("TR", "Trip"),
                            ("HOME", "Home"),
                            ("COUP", "Couple"),
                            ("OTHERS", "Others"),
                        ],
                        default="TR",
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
