# Generated by Django 5.0.1 on 2024-01-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_profile_id_profile_profile_id_debt_friendship"),
    ]

    operations = [
        migrations.DeleteModel(name="Debt",),
    ]
